version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    # Mounting the current directory for development debugging; remove in production if not needed.
    volumes:
      - .:/app
    # Load variables from .env file. Create .env at the root with your environment-specific settings.
    env_file:
      - .env
    # Optional: Override or add any environment variables here
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      # To run in development using Flask's built-in server, you can override CMD in Dockerfile:
      # - FLASK_ENV=development