name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  # Optionally, you can also trigger on pull requests or schedule runs:
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ninadranade/ai-poem-generator:latest

name: Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ninadranade/ai-poem-generator:latest .

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@v0.6.0
        with:
          image-ref: ninadranade/ai-poem-generator:latest
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
