name: CI/CD - Integration Test

on:
  push:
    branches:
      - new-code
  pull_request:
    branches:
      - new-code

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t ai-poem-generator:ci .

      - name: Run Container
        run: |
          # Run container in detached mode
          docker run -d --rm --name ai_test_container -p 5000:5000 ai-poem-generator:ci
          
          # Wait for the container to be ready (adjust sleep if necessary or implement a retry loop)
          sleep 10

      - name: Test Application Health
        run: |
          # Test the homepage (or a health endpoint if available)
          curl -f http://localhost:5000 || (echo "Application did not respond as expected" && exit 1)

      - name: Stop and Remove Container
        run: |
          docker stop ai_test_container
