name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ninadranade/ai-poem-generator:latest

      - name: Run container for integration tests
        run: |
          docker run -d --rm --name test_container -p 5000:5000 ninadranade/ai-poem-generator:latest
          # Allow time for the container to start up
          sleep 10

      - name: Test Application Health
        run: |
          # Perform an HTTP GET request to the application's homepage.
          # If this check fails, output logs and exit with failure.
          curl -f http://localhost:5000 || (docker logs test_container && exit 1)

      - name: Stop container
        run: docker stop test_container

      - name: Push Docker Image
        run: docker push ninadranade/ai-poem-generator:latest
